### ISSUE TITLE
Função de ciclos dando problema

### ISSUE THREAD

**Issue by ghost** [viniciuscbb/bot-sinais-2.0#13]
Olá, na nova atualização em que foi adicionado Ciclos, ele está dando o seguinte erro:

Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\AppData\Local\Programs\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\AppData\Local\Programs\Python\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 472, in entradas
    resultado, lucro = API.check_win_digital_v2(id)
  File "C:\iqoptionapi\stable_api.py", line 1200, in check_win_digital_v2
    while self.get_async_order(buy_order_id)["position-changed"] == {}:
  File "C:\iqoptionapi\stable_api.py", line 1300, in get_async_order
    return self.api.order_async[buy_order_id]
TypeError: unhashable type: 'dict'

**Comment by viniciuscbb** [comment]
Mas nem tem essa função no bot
