### ISSUE TITLE
Bot não funciona: Traceback Errors

### ISSUE THREAD

**Issue by oppalla** [viniciuscbb/bot-sinais-2.0#4]
> >> Conectado com sucesso!
> 
> Saldo da conta demo: $10,000.00
> Traceback (most recent call last):
>   File "C:\Users\dagger\Desktop\bot-sinais-2.0-master\bot-sinais-2.0-master\main.py", line 474, in <module>
>     buscarMenor()
>   File "C:\Users\dagger\Desktop\bot-sinais-2.0-master\bot-sinais-2.0-master\main.py", line 166, in buscarMenor
>     dif = int((datetime.strptime(timeNow, f) - datetime.strptime(horario, f)).total_seconds() / 60)
>   File "C:\Users\dagger\AppData\Local\Programs\Python\Python39\lib\_strptime.py", line 568, in _strptime_datetime
>     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
>   File "C:\Users\dagger\AppData\Local\Programs\Python\Python39\lib\_strptime.py", line 349, in _strptime
>     raise ValueError("time data %r does not match format %r" %
> ValueError: time data 'HORA:00' does not match format '%H:%M:%S'

**Comment by oppalla** [comment]
o que está havendo? estou fazendo algo de errado no passo a passo?

**Comment by oppalla** [comment]
@jeffex @viniciuscbb

**Comment by oppalla** [comment]
descobri. tinha que remover o TEMPO;PAR;HORA;DIRECAO da lista de sinais. desculpem a perturbação.
